language: node_js
node_js:
  - "8"
  - "node"
sudo: enabled
os: linux


before_install:
  - npm install -g ts-node
  - npm install -g typescript
install:
  - sudo npm install

script:
  - ./scripts/runReport.sh
